import pandas as pd
import gensim
from gensim.utils import simple_preprocess
from gensim.parsing.preprocessing import STOPWORDS
from nltk.stem import WordNetLemmatizer, SnowballStemmer
from nltk.stem.porter import *
import numpy as np
import nltk

from gensim.models.coherencemodel import CoherenceModel
from gensim.models.ldamodel import LdaModel
from gensim.corpora.dictionary import Dictionary






def lemmatize_stemming(text):
    """Return lemmetized and stemmed text"""
    stemmer = SnowballStemmer('english')
    return stemmer.stem(WordNetLemmatizer().lemmatize(text, pos='v'))


def preprocess(text):
    result = []
    stopwords = ['a',
         'about',
         'above',
         'across',
         'accredited',
         'affirmative',
         'after',
         'afterwards',
         'again',
         'against',
         'age',
         'agency',
         'all',
         'almost',
         'alone',
         'along',
         'already',
         'also',
         'although',
         'always',
         'am',
         'among',
         'amongst',
         'amoungst',
         'amount',
         'an',
         'and',
         'another',
         'any',
         'anyhow',
         'anyone',
         'anything',
         'anyway',
         'anywhere',
         'apply',
         'application',
         'applications',
         'applicant',
         'applicants',
         'are',
         'around',
         'as',
         'at',
         'bachelor',
         'bachelors',
         "bachelor's",
         'be',
         'became',
         'because',
         'become',
         'becomes',
         'becoming',
         'been',
         'before',
         'beforehand',
         'behind',
         'being',
         'below',
         'benefit',
         'benefits',
         'beside',
         'besides',
         'between',
         'beyond',
         'bill',
         'both',
         'bonus',
         'bottom',
         'but',
         'by',
         'call',
         'can',
         'candid',
         'candidates',
         'candidate',
         'cannot',
         'cant',
         'card',
         'career',
         'certificate',
         'certification',
         'ciber',
         'ciber',
         'cisco',
         'citizen',
         'citizenship',
         'click',
         'client',
         'co',
         'college',
         'color',
         'com',
         'company',
         'compensation',
         'computer',
         'con',
         'consultnet',
         'contract',
         'could',
         'couldnt',
         'country',
         'cry',
         'cybercoder',
         'cybercoders',
         'de',
         'degree',
         'dental',
         'describe',
         'description',
         'detail',
         'did',
         'didn',
         'diploma',
         'direct',
         'disability',
         'do',
         'does',
         'doesn',
         'doing',
         'don',
         'done',
         'down',
         'due',
         'duration',
         'during',
         'each',
         'east',
         'education',
         'eg',
         'eight',
         'either',
         'eleven',
         'eliassen',
         'eligible',
         'eligibility',
         'else',
         'elsewhere',
         'email',
         'employ',
         'employees',
         'employee',
         'employer',
         'employment',
         'empty',
         'enough',
         'equal',
         'etc',
         'even',
         'ever',
         'every',
         'everyone',
         'everything',
         'everywhere',
         'except',
         'experience',
         'experiences',
         'experienced',
         'experienced',
         'experience',
         'fahrenheit',
         'federal',
         'few',
         'fico',
         'fifteen',
         'fifty',
         'fill',
         'find',
         'fire',
         'first',
         'five',
         'for',
         'former',
         'formerly',
         'forty',
         'found',
         'four',
         'from',
         'full',
         'fulltime',
         'further',
         'gender',
         'get',
         'give',
         'global',
         'go',
         'govern',
         'government',
         'green',
         'greencard',
         'had',
         'half',
         'has',
         'hasnt',
         'have',
         'he',
         'hence',
         'her',
         'here',
         'hereafter',
         'hereby',
         'herein',
         'hereupon',
         'hers',
         'herself',
         'him',
         'himself',
         'hire',
         'hired',
         'his',
         'how',
         'however',
         'hour',
         'hours',
         'hundred',
         'i',
         'identity',
         'ie',
         'if',
         'immediate',
         'immediately',
         'in',
         'inc',
         'include',
         'indeed',
         'insurance',
         'interest',
         'into',
         'is',
         'it',
         'its',
         'itself',
         'jobs',
         'job',
         'just',
         'keep',
         'kg',
         'km',
         'last',
         'latter',
         'latterly',
         'law',
         'least',
         'less',
         'life',
         'linkedin',
         'ltd',
         'local',
         'location',
         'made',
         'make',
         'many',
         'master',
         'masters',
         "master's",
         'may',
         'me',
         'meanwhile',
         'medical',
         'might',
         'mill',
         'mine',
         'minimum',
         'nminimum',
         'month',
         'months',
         'monthly',
         'more',
         'moreover',
         'most',
         'mostly',
         'move',
         'much',
         'must',
         'my',
         'myself',
         'name',
         'namely',
         'nation',
         'national',
         'needs',
         'need',
         'neither',
         'never',
         'nevertheless',
         'next',
         'nine',
         'nkforce',
         'no',
         'nobody',
         'none',
         'noone',
         'nor',
         'north',
         'not',
         'nothing',
         'now',
         'nowhere',
         'of',
         'off',
         'offer',
         'often',
         'on',
         'once',
         'one',
         'only',
         'onto',
         'opportunity',
         'or',
         'oracle',
         'other',
         'others',
         'otherwise',
         'our',
         'ours',
         'ourselves',
         'out',
         'over',
         'own',
         'part',
         'pay',
         'payroll',
         'per',
         'perhaps',
         'permanent',
         'phd',
         'please',
         'position',
         'pregnancy',
         'pregnant',
         'preferred',
         'protect',
         'put',
         'qualification',
         'qualifications',
         'qualify',
         'quite',
         'race',
         'rather',
         're',
         'really',
         'refer',
         'referral',
         'regarding',
         'reimbursement',
         'reimburse',
         'religion',
         'require',
         'requires',
         'required',
         'nrequired',
         'requirement',
         'recruiter',
         'recruit',
         'resume',
         'rights',
         'right',
         'robert',
         'salesforce',
         'same',
         'sap',
         'say',
         'school',
         'see',
         'seem',
         'seemed',
         'seeming',
         'seems',
         'senior',
         'serious',
         'several',
         'sex',
         'sexual',
         'she',
         'should',
         'show',
         'side',
         'since',
         'sincere',
         'six',
         'sixty',
         'skill',
         'skills',
         'so',
         'some',
         'somehow',
         'someone',
         'something',
         'sometime',
         'sometimes',
         'somewhere',
         'south',
         'staff',
         'state',
         'states',
         'still',
         'such',
         'summary',
         'system',
         'take',
         'tek',
         'teksystems',
         'teksystem',
         'teksystems',
         'teksystem',
         'teksystems:',
         'ten',
         'than',
         'that',
         'the',
         'their',
         'them',
         'themselves',
         'then',
         'thence',
         'there',
         'thereafter',
         'thereby',
         'therefore',
         'therein',
         'thereupon',
         'these',
         'they',
         'thick',
         'thin',
         'third',
         'this',
         'those',
         'though',
         'three',
         'through',
         'throughout',
         'thru',
         'thus',
         'to',
         'together',
         'too',
         'top',
         'toward',
         'towards',
         'transfer',
         'twelve',
         'twenty',
         'two',
         'un',
         'under',
         'unless',
         'until',
         'up',
         'upon',
         'us',
         'used',
         'using',
         'various',
         'very',
         'veteran',
         'via',
         'vision',
         'was',
         'we',
         'well',
         'were',
         'west',
         'what',
         'whatever',
         'when',
         'whence',
         'whenever',
         'where',
         'whereafter',
         'whereas',
         'whereby',
         'wherein',
         'whereupon',
         'wherever',
         'whether',
         'which',
         'while',
         'whither',
         'who',
         'whoever',
         'whole',
         'whom',
         'whose',
         'why',
         'will',
         'with',
         'within',
         'without',
         'world',
         'would',
         'www',
         'year',
         'years',
         'yet',
         'you',
         'your',
         'yours',
         'yourself',
         'yourselves',
         'new',
         'york',
         'los',
         'angeles',
         'chicago',
         'houston',
         'philadelphia',
         'phoenix',
         'san',
         'antonio',
         'san',
         'diego',
         'dallas',
         'san',
         'jose',
         'austin',
         'jacksonville',
         'san',
         'francisco',
         'indianapolis',
         'columbus',
         'fort',
         'worth',
         'charlotte',
         'seattle',
         'denver',
         'el',
         'paso',
         'detroit',
         'washington',
         'boston',
         'memphis',
         'nashville',
         'portland',
         'oklahoma',
         'city',
         'las',
         'vegas',
         'baltimore',
         'louisville',
         'milwaukee',
         'albuquerque',
         'tucson',
         'fresno',
         'sacramento',
         'kansas',
         'city',
         'long',
         'beach',
         'mesa',
         'atlanta',
         'colorado',
         'springs',
         'virginia',
         'beach',
         'raleigh',
         'omaha',
         'miami',
         'oakland',
         'minneapolis',
         'tulsa',
         'wichita',
         'new',
         'orleans',
         'arlington',
         'alabama',
         'alaska',
         'arizona',
         'arkansas',
         'california',
         'colorado',
         'connecticut',
         'delaware',
         'florida',
         'georgia',
         'hawaii',
         'idaho',
         'illinois',
         'indiana',
         'iowa',
         'kansas',
         'kentucky',
         'louisiana',
         'maine',
         'maryland',
         'massachusetts',
         'miami',
         'michigan',
         'minnesota',
         'mississippi',
         'missouri',
         'montana',
         'nebraska',
         'nevada',
         'new',
         'hampshire',
         'new',
         'jersey',
         'new',
         'mexico',
         'new',
         'york',
         'north',
         'carolina',
         'north',
         'dakota',
         'ohio',
         'oklahoma',
         'oregon',
         'pennsylvania',
         'rhode',
         'island',
         'south',
         'carolina',
         'south',
         'dakota',
         'tennessee',
         'texas',
         'utah',
         'vermont',
         'virginia',
         'washington',
         'west',
         'virginia',
         'wisconsin',
         'wyoming',
         'america',
         'u.s.',
         'asia']
    for token in gensim.utils.simple_preprocess(text):
        if token not in stopwords and len(token) > 2:
            result.append(lemmatize_stemming(token))
    return result




def remove_brackets(list1):
    """Remove [] from text"""
    return str(list1).replace('[','').replace(']','')






#Revmoe Punctuations that definitely won't contribute
def remove_punctuation(s):
    #Phase 1, handle punctuation.
    # Directly removable
    #  '/', ',', '\', '|',
    for char in ['/', '//', '|', '?', '(', ')', '{', '}', '[', ']', ',', '.', '-', '!',
                 '~', '_', '@', ':', '55', '*', ';', '14']:
        s = s.replace(char, " ")
    s.strip()
    #remove those consists of only punctuation and number
    s = filter(lambda x: not re.match("[0-9~!@#$%^&*()_\-+{}\":;\']+", x), s.split())
    return ' '.join(s)


def remove_stop_words(text):
    
    """Remove stopwords from job titles"""
    
    result = []
    
    jobtitle_stopwords = ['a',
                          'absence',
                          'accepted',
                          'accepting',
                          'adoption',
                          'advantage',
                          'albany',
                          'allstate',
                          'alteryx',
                          'alto',
                          'ana',
                          'and',
                          'angeles',
                          'anywhere',
                          'arher',
                          'apigee',
                          'appleton',
                          'applications',
                          'apply',
                          'at',
                          'atlanta',
                          'austin',
                          'available',
                          'availability',
                          'az',
                          'az!',
                          'bare',
                          'bartender',
                          'basking',
                          'bay',
                          'bay!!',
                          'beach',
                          'beautiful',
                          'bench',
                          'benefi',
                          'benefits',
                          'benefit!',
                          'bethlehem',
                          'berkeley',
                          'berlin',
                          'bilingual',
                          'bloomington',
                          'boarding',
                          'bonus',
                          'bonus!',
                          'boston',
                          'bothell',
                          'brentwood',
                          'bridgewater',
                          'briefing',
                          'brooklyn',
                          'buckhead',
                          'buffalo',
                          'burbank',
                          'ca',
                          'call',
                          'california',
                          'cambridge',
                          'campus',
                          'canada',
                          'candidates',
                          'candidate',
                          'carrollton',
                          'career',
                          'certification',
                          'castle',
                          'chai',
                          'charlotte',
                          'charles',
                          'charleston',
                          'chesapeake',
                          'chesterbrook',
                          'chicago',
                          'china',
                          'chef',
                          'chester',
                          'chicago',
                          'chief',
                          'chinese',
                          'cincinnati',
                          'cisco',
                          'city',
                          'clearance',
                          'cleared',
                          'click',
                          'cloverleaf',
                          'co',
                          'collins',
                          'college',
                          'columbia',
                          'colorado',
                          'columbus',
                          'come',
                          'commissioning',
                          'commissions',
                          'concord',
                          'contract!!!!!',
                          'contract',
                          'contact',
                          'contracting',
                          'contractor',
                          'corner',
                          'costa',
                          'creek',
                          'cucumber',
                          'dallas',
                          'danbury',
                          'date',
                          'day',
                          'days',
                          'dayforce',
                          'daytona',
                          'decommision',
                          'deerfield',
                          'degree',
                          'denver',
                          'des',
                          'detroit',
                          'diego',
                          'diligence',
                          'diversity',
                          'do',
                          'dodgeville',
                          'dover',
                          'duck',
                          'due',
                          'dulles',
                          'duration',
                          'durham',
                          'direct',
                          'dirext',
                          'east',
                          'education',
                          'edwards',
                          'eggplant',
                          'elkton',
                          'elyria',
                          'email',
                          'employment',
                          'english',
                          'entry',
                          'enrollments',
                          'espresso',
                          'exclusive',
                          'exp_____',
                          'exp@philadelphia',
                          'f1',
                          'falls',
                          'fargo',
                          'farmington',
                          'fast',
                          'feed',
                          'fico',
                          'fin',
                          'fixed',
                          'florham',
                          'florida',
                          'fluent',
                          'for',
                          'forest',
                          'forms',
                          'fort',
                          'foster',
                          'francisco'
                          'frankfort',
                          'fremont',
                          'french',
                          'friday',
                          'fte',
                          'full-time',
                          'full',
                          'fulltime',
                          'fully',
                          'ga',
                          'georgia',
                          'german',
                          'glassdoor',
                          'goldengate',
                          'graduates',
                          'great',
                          'greenbelt',
                          'groovy',
                          'growing',
                          "hl7': 2",
                          'half',
                          'hampton',
                          'hana_contract_',
                          'harrisburg',
                          'hartford',
                          'heights',
                          'high',
                          'highly',
                          'higher',
                          'hill',
                          'hills',
                          'hire',
                          'hiring',
                          'hitachi',
                          'holtsville',
                          'hour',
                          'hourly',
                          'hours',
                          'houston',
                          'huntersville',
                          'illinois',
                          'in',
                          'implementation',
                          'immediate',
                          'immediately!',
                          'incentive',
                          'india',
                          'indiana',
                          'intern',
                          'internship',
                          'interview',
                          'interviews',
                          'interviewing',
                          'income',
                          'incomee',
                          'indianapolis',
                          'invoice',
                          'irving',
                          'irvine',
                          'is',  
                          'j2ee',
                          'janitor',
                          'january',
                          'japanese',
                          'jenkins',
                          'jersey',
                          'job',
                          'join',
                          'jose',
                          'jr',
                          'junior',
                          'juniper',
                          'kalamazoo',
                          'kegonsa',
                          'kennesaw',
                          'kensington',
                          'king',
                          'knoxville',
                          'ky',
                          'ladera',
                          'lakeland',
                          'las',
                          'lending',
                          'life',
                          'linkedin',
                          'lisa',
                          'local',
                          'locals',
                          'location',
                          'locations',
                          'logging',
                          'long',
                          'longterm',
                          'looking',
                          'los',
                          'louisville',
                          'loyalty',
                          'louis',
                          'malborough',
                          'mandarin',
                          'mandatory',
                          'manhattan',
                          'marshall',
                          'massachusetts',
                          'medicare',
                          'melville',
                          'memphis',
                          'menomonee',
                          'mesa',
                          'mettawa',
                          'mi',
                          'michael',
                          'miami',
                          'michigan',
                          'mid',
                          'middleton',
                          'midlevel',
                          'midnight',
                          'minnesota',
                          'minnetonka',
                          'minneapolis',
                          'mn',
                          'mo',
                          'mocha',
                          'moines',
                          'monday',
                          'monroe',
                          'month',
                          'months',
                          'montnths',
                          'montreal',
                          'montvale',
                          'mountain',
                          'moving',
                          'multiple',
                          'must',
                          'naperville',
                          'nashville',
                          'native',
                          'nc',
                          'need',
                          'needed',
                          'new!',
                          'new',
                          'nh',
                          'nightshift',
                          'north',
                          'northborough',
                          'northridge',
                          'nj',
                          'ny',
                          'nyc',
                          'oakland',
                          'of',
                          'oh',
                          'ohio',
                          'ok',
                          'okc',
                          'omaha',
                          'on',
                          'oklahoma',
                          'onbase',
                          'only',
                          'only!',
                          'onsite',
                          'open',
                          'openshift',
                          'opening',
                          'openings',
                          'opportunity',
                          'opportunityl',
                          'option',
                          'openings!',
                          'opportunity',
                          'opportunities',
                          'or',
                          'orlando',
                          'our',
                          'overnight',
                          'owner',
                          'paid',
                          'palo',
                          'paris',
                          'part',
                          'partial',
                          'passion!',
                          'paul',
                          'pay',
                          'payroll',
                          'per',
                          'phd',
                          'philadelphia',
                          'phoenix',
                          'phone',
                          'pittsburgh',
                          'pleasanton',
                          'peoplesoft',
                          'portland',
                          'portsmouth',
                          'portuguese',
                          'position',
                          'perm',
                          'permanent',
                          'positions',
                          'practice',
                          'prelude',
                          'preferred',
                          'prepayment',
                          'presales',
                          'princeton',
                          'profit',
                          'promotion',
                          'protected',
                          'prussia',
                          'qualified',
                          'quick',
                          'quickly!',
                          'raleigh',
                          'rate',
                          'rate:',
                          'recruiting',
                          'recruitment',
                          'redmond',
                          'redwood',
                          'referral',
                          'relocate',
                          'relocation',
                          'remote!',
                          'remote**',
                          'reopened',
                          'residential',
                          'retirement',
                          'required',
                          'required:',
                          'required**',
                          'required***',
                          'required!',
                          'requirement',
                          'requirements',
                          "req'd",
                          'resident',
                          'residents',
                          'richardson',
                          'richfield',
                          'richmond',
                          'ridge',
                          'river',
                          'riversand',
                          'robert',
                          'rock',
                          'rockville',
                          'rocky',
                          'role',
                          'role!',
                          'roles::::multiple',
                          'salary',
                          'salesforce',
                          'saleforce',
                          'salesforcedx',
                          'salem',
                          'san',
                          'santa',
                          'sap',
                          'sat',
                          'saturday',
                          'sc',
                          'schaumburg',
                          'scottsdale',
                          'seattle',
                          'selection',
                          'senior',
                          'senior___________',
                          'shanghai',
                          'sharing',
                          'shift',
                          'sidney',
                          'shakopee',
                          'shift',
                          'sign',
                          'sitecore',
                          'snowflake',
                          'southern',
                          'sox',
                          'speaker',
                          'spring',
                          'springs',
                          'sr',
                          'stamford',
                          'startup',
                          'st',
                          'sterile',
                          'sterling',
                          'student',
                          'subcontract',
                          'substation',
                          'summer',
                          'sun',
                          'syracuse',
                          'talend',
                          'tampa',
                          'temp',
                          'temporary',
                          'terrace',
                          'term',
                          'texas',
                          'territory',
                          'transfers',
                          'transition',
                          'travel',
                          'that',
                          'the',
                          'this',
                          'thunderhead',
                          'tickets',
                          'time',
                          'tn',
                          'today',
                          'tomorrow',
                          'trainee',
                          'travelers',
                          'tri',
                          'ts',
                          'tx',
                          'tyson',
                          'uk',
                          'university',
                          'usc',
                          'va',
                          'vancouver',
                          'valley',
                          'vegas',
                          'vernon',
                          'vietnamese',
                          'view',
                          'virginia',
                          'visa',
                          "visa's",
                          'w2',
                          'wa',
                          'was',
                          'washington',
                          'waterfall',
                          'we',
                          'week',
                          'west',
                          'westbury',
                          'westlake',
                          'wi',
                          'wilmington',
                          'woodcliff',
                          'work',
                          'workday',
                          'worth',
                          'year',
                          'years',
                          'york',
                          'yr',
                          'yrs',
                         '12',
                         'z',
                         '13']
    
    for word in text.split():
        
        if word not in jobtitle_stopwords:
            result.append(word)
    result = ' '.join(result)
    return result








#Find the optimal number of topics
def compute_coherence_values(dictionary, corpus, texts, limit, start=2, step=3):
    """
    Compute c_v coherence for various number of topics

    Parameters:
    ----------
    dictionary : Gensim dictionary
    corpus : Gensim corpus
    texts : List of input texts
    limit : Max num of topics

    Returns:
    -------
    model_list : List of LDA topic models
    coherence_values : Coherence values corresponding to the LDA model with respective number of topics
    """
    coherence_values = []
    model_list = []
    for num_topics in range(start, limit, step):
        model=gensim.models.LdaMulticore(corpus=corpus, id2word=dictionary, 
                                         num_topics=num_topics, chunksize=100,
                                        passes=20, workers=4)
        model_list.append(model)
        coherencemodel = CoherenceModel(model=model, texts=texts, dictionary=dictionary, coherence='c_v')
        coherence_values.append(coherencemodel.get_coherence())

    return model_list, coherence_values



def show_topics_sentences(ldamodel, corpus, texts):
    """Returns df with topics and descriptions"""
    sent_topics_df = pd.DataFrame()

    # Get main topic in each document
    for i, row in enumerate(ldamodel[corpus]):
        row = sorted(row, key=lambda x: (x[1]), reverse=True)
        # Get the Dominant topic, Perc Contribution and Keywords for each document
        for j, (topic_num, prop_topic) in enumerate(row):
            if j == 0:  # => dominant topic
                wp = ldamodel.show_topic(topic_num)
                topic_keywords = ", ".join([word for word, prop in wp])
                sent_topics_df = sent_topics_df.append(pd.Series([int(topic_num), round(prop_topic,4), topic_keywords]), ignore_index=True)
            else:
                break
    sent_topics_df.columns = ['Dominant_Topic', 'Perc_Contribution', 'Topic_Keywords']

    # Add original text to the end of the output
    contents = pd.Series(texts)
    sent_topics_df = pd.concat([sent_topics_df, contents], axis=1)
    return(sent_topics_df)












